[c]1[c][c][c]n[c]1.[C][C][N][C]=O	0692_0434_updated/0434_frag.xyz
O=C([N]c1[c][c][c]n[c]1)[N]c1[c][c][c][c][c]1	0692_0434_updated/0434_orig.xyz
[C][C][C]=[C].[N]	0692_0434_updated/0434_overlap.xyz
[C][C][C]N([C][C][N]C(=O)[C])[C]	0692_0434_updated/0692_frag.xyz
[C]c1[c][c][c]c([c]1)[C]N1[C][C]N([C][C]1)C(=O)[C]	0692_0434_updated/0692_orig.xyz
[C]/[C]=[C]\[C].[C]	0692_0434_updated/0692_overlap.xyz
